//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Game_GridUtilityWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("GridUtility");
		L.RegFunction("ToPosition", ToPosition);
		L.RegConstant("SIZE", 0.319999992847443);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ToPosition(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 2);
			UnityEngine.Vector2 o = Game.GridUtility.ToPosition(arg0, arg1);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

